BC-478 | Resolve port conflicts, update environment settings, add debug logs, and improve Docker configurations

diff --git a/.github/workflows/test-compose.yml b/.github/workflows/test-compose.yml
--- a/.github/workflows/test-compose.yml
+++ b/.github/workflows/test-compose.yml
@@ -206,7 +206,8 @@ jobs:
         with:
           kube_namespace: ${{ secrets.KUBE_NAMESPACE_LAA_FEE_SCHEME_API_UAT }}
           pod_selector: app.kubernetes.io/name=laa-fee-scheme-api
-          local_port: "8085"
+          local_port: "8095"
+          remote_port: "8085"
           pid_env_var: PORT_FORWARD_PID
           wait_label: fsp-api
 
@@ -224,7 +225,7 @@ jobs:
         with:
           kube_namespace: ${{ secrets.KUBE_NAMESPACE_LAA_SUBMIT_A_BULK_CLAIM_UAT }}
           pod_selector: app=uat-e2e-testing-pda-proxy
-          local_port: "8086"
+          local_port: "8186"
           remote_port: "8080"
           pid_env_var: PORT_FORWARD_PID
           wait_label: pda-api
@@ -251,9 +252,9 @@ jobs:
         run: |
           cat <<EOF > .env
           UI_BASE_URL=http://127.0.0.1:8082
-          FSP_API_BASE_URL=http://127.0.0.1:8085
+          FSP_API_BASE_URL=http://127.0.0.1:8095
           FSP_API_TOKEN=${{ secrets.FSP_API_TOKEN }}
-          PROVIDER_API=http://127.0.0.1:8086/api/v1/provider-offices
+          PROVIDER_API=http://127.0.0.1:8186/api/v1/provider-offices
           PROVIDER_API_KEY=${{ secrets.PDA_API_TOKEN }}
           DSTEW_API_BASE_URL=127.0.0.1:8080
           DSTEW_API_TOKEN=f67f968e-b479-4e61-b66e-f57984931e56
@@ -392,15 +393,16 @@ jobs:
       
           echo "=== OIDC ==="
           curl -sS -w '\nHTTP_STATUS:%{http_code}\n' http://127.0.0.1:9000
+          curl -sS -w '\nHTTP_STATUS:%{http_code}\n' http://127.0.0.1:9000
           
           echo "=== OIDC (host) ==="
           curl -sS -w '\nHTTP_STATUS:%{http_code}\n' http://oidc:9000
           
           echo "=== FSP (PF) ==="
-          curl -sS -w '\nHTTP_STATUS:%{http_code}\n' http://127.0.0.1:8085/swagger-ui/index.html
+          curl -sS -w '\nHTTP_STATUS:%{http_code}\n' http://127.0.0.1:8095/v3/api-docs
           
           echo "=== PDA (PF) ==="
-          curl -sS -w '\nHTTP_STATUS:%{http_code}\n' http://127.0.0.1:8086/swagger-ui/index.html
+          curl -sS -w '\nHTTP_STATUS:%{http_code}\n' http://127.0.0.1:8186/v3/api-docs
           
           
           exit 0
@@ -410,9 +412,9 @@ jobs:
         run: |
           set +e
           echo "=== PIDs using port 8086 ==="
-          sudo lsof -i :8086 -t || echo "No processes found on port 8086"
-          sudo lsof -i :8086 || echo "Detailed lsof failed"
-          sudo netstat -tlnp | grep :8086 || echo "No netstat entries for port 8086"
+          sudo lsof -i :8186 -t || echo "No processes found on port 8086"
+          sudo lsof -i :8186 || echo "Detailed lsof failed"
+          sudo netstat -tlnp | grep :8186 || echo "No netstat entries for port 8086"
           exit 0
 
       - name: Login
@@ -421,7 +423,7 @@ jobs:
 
       - name: Run tests
         shell: bash
-        run: npm run test -- --tags "${{ inputs.test_annotation || '@stable'}}"  --parallel 4 --retry 1
+        run: npm run test -- --tags "${{ inputs.test_annotation || '@stable'}}"  --parallel 2 --retry 1
 
       - name: Logs for OIDC
         if: failure()
@@ -436,12 +438,12 @@ jobs:
       - name: Logs for Claims API
         if: failure()
         run: |
-          docker logs --tail 500 data-claims-api-app
+          docker logs --tail 1000 data-claims-api-app
 
       - name: Logs for Claims Event Service
         if: failure()
         run: |
-          docker logs --tail 500 data-claims-event-service-app
+          docker logs --tail 1000 data-claims-event-service-app
 
       - name: Teardown docker containers
         if: always()
@@ -456,7 +458,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: ui-accessibility-reports
+          name: test-reports
           path: reports
           if-no-files-found: warn
 
